/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'prasad' at '26/2/17 11:02 PM' with Gradle 3.2.1
 *
 * @author prasad, @date 26/2/17 11:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
